import type { Category, Source } from "../types";

export interface CategoryKeywords {
  primaryKeywords: string[];
  secondaryKeywords: string[];
  sourceHints: Record<string, Source>;
}

export const KEYWORD_MAP: Record<Exclude<Category, "other">, CategoryKeywords> =
  {
    ai: {
      primaryKeywords: [
        "llm",
        "gpt",
        "gpt-4",
        "gpt-5",
        "openai",
        "anthropic",
        "claude",
        "gemini",
        "copilot",
        "machine-learning",
        "deep-learning",
        "neural-network",
        "transformer",
        "diffusion",
        "langchain",
        "rag",
        "fine-tuning",
        "fine-tune",
        "chatgpt",
        "midjourney",
        "stable-diffusion",
        "hugging-face",
        "huggingface",
        "ollama",
        "llamaindex",
        "vector-database",
        "embedding",
        "ai-agent",
        "mcp",
        "model-context-protocol",
      ],
      secondaryKeywords: [
        "ai",
        "ml",
        "nlp",
        "generative",
        "prompt",
        "inference",
        "training",
        "model",
        "token",
        "completion",
        "chat-completion",
        "retrieval-augmented",
        "semantic-search",
        "text-generation",
        "image-generation",
        "multimodal",
        "lora",
        "rlhf",
        "attention",
        "bert",
        "sagemaker",
        "bedrock",
      ],
      sourceHints: {
        machinelearning: "reddit",
        LocalLLaMA: "reddit",
        artificial: "reddit",
      },
    },

    security: {
      primaryKeywords: [
        "vulnerability",
        "cve",
        "exploit",
        "malware",
        "ransomware",
        "zero-day",
        "0day",
        "authentication",
        "authorization",
        "encryption",
        "tls",
        "ssl",
        "firewall",
        "pentest",
        "penetration-testing",
        "owasp",
        "xss",
        "sql-injection",
        "csrf",
        "rbac",
        "oauth",
        "jwt",
        "cybersecurity",
        "infosec",
        "soc",
        "siem",
        "ids",
        "ips",
      ],
      secondaryKeywords: [
        "security",
        "secure",
        "attack",
        "breach",
        "patch",
        "hardening",
        "audit",
        "compliance",
        "cryptography",
        "certificate",
        "phishing",
        "botnet",
        "ddos",
        "sandbox",
        "waf",
        "threat",
        "privilege-escalation",
      ],
      sourceHints: {
        netsec: "reddit",
        cybersecurity: "reddit",
      },
    },

    architecture: {
      primaryKeywords: [
        "microservice",
        "microservices",
        "monolith",
        "event-driven",
        "cqrs",
        "ddd",
        "domain-driven",
        "distributed-system",
        "distributed-systems",
        "load-balancer",
        "load-balancing",
        "kubernetes",
        "k8s",
        "docker",
        "container",
        "terraform",
        "infrastructure-as-code",
        "ci/cd",
        "ci-cd",
        "service-mesh",
        "istio",
        "envoy",
        "helm",
        "argocd",
        "gitops",
      ],
      secondaryKeywords: [
        "scalability",
        "scaling",
        "architecture",
        "infrastructure",
        "devops",
        "orchestration",
        "deployment",
        "pipeline",
        "observability",
        "monitoring",
        "grafana",
        "prometheus",
        "kafka",
        "rabbitmq",
        "message-queue",
        "api-gateway",
        "reverse-proxy",
        "nginx",
        "caddy",
        "grpc",
        "protobuf",
        "system-design",
      ],
      sourceHints: {
        devops: "reddit",
        kubernetes: "reddit",
      },
    },

    "react-nextjs": {
      primaryKeywords: [
        "react",
        "reactjs",
        "react.js",
        "nextjs",
        "next.js",
        "remix",
        "gatsby",
        "jsx",
        "tsx",
        "hooks",
        "usestate",
        "useeffect",
        "usememo",
        "server-components",
        "rsc",
        "vercel",
        "react-server",
        "react-query",
        "tanstack",
        "zustand",
        "redux",
        "react-router",
        "app-router",
        "pages-router",
      ],
      secondaryKeywords: [
        "component",
        "virtual-dom",
        "hydration",
        "ssr",
        "ssg",
        "isr",
        "suspense",
        "concurrent",
        "fiber",
        "tailwindcss",
        "tailwind",
        "shadcn",
        "radix",
        "framer-motion",
        "storybook",
      ],
      sourceHints: {
        reactjs: "reddit",
        nextjs: "reddit",
      },
    },

    go: {
      primaryKeywords: [
        "golang",
        "go-lang",
        "goroutine",
        "goroutines",
        "gomodule",
        "go-module",
        "gopher",
        "goland",
        "go1.",
      ],
      secondaryKeywords: [
        "concurrency",
        "channel",
        "defer",
        "interface{}",
        "struct",
        "gin",
        "echo",
        "fiber",
        "cobra",
        "viper",
      ],
      sourceHints: {
        golang: "reddit",
      },
    },

    aws: {
      primaryKeywords: [
        "aws",
        "amazon-web-services",
        "lambda",
        "s3",
        "ec2",
        "ecs",
        "eks",
        "cloudfront",
        "dynamodb",
        "sagemaker",
        "bedrock",
        "cdk",
        "cloudformation",
        "cloudwatch",
        "fargate",
        "api-gateway",
        "route53",
        "rds",
        "aurora",
        "cognito",
        "sns",
        "sqs",
        "eventbridge",
        "step-functions",
        "amplify",
      ],
      secondaryKeywords: [
        "amazon",
        "iam",
        "vpc",
        "subnet",
        "elastic",
        "elasticache",
        "redshift",
        "glue",
        "athena",
        "kinesis",
        "lightsail",
        "beanstalk",
      ],
      sourceHints: {
        aws: "reddit",
      },
    },
  };
